### ISSUE TITLE
Curve disappears when Codepen refreshes

### ISSUE THREAD

**Issue by lifeinchords** [legomushroom/mojs-curve-editor#10]
Hi there,
This tool is so awesome, thanks for taking the time to make it.

I'm trying to use the `isSaveState` property on the curve editor inside a Codepen.
When I make a change to the source and the page refreshes, the curve I drew disappears.
My guess is this is a limitation of using Codepen. Is this intentional, or am I making a mistake in how I'm using it?

An example pen is here:  https://codepen.io/lifeinchords/pen/vgGbrr

Thanks Oleg!

**Comment by legomushroom** [comment]
Hi Steven!

Thanks, happy to hear that! The curve editor uses the name as a key in localStrorage and since you creating a new name uniformly at random on each page refresh - it starts over with new state each time. So you can just create a name once and use it. Please let me know if it helps, I had no issues to use the curve editor with Codepen.

Cheers!

**Comment by lifeinchords** [comment]
Oh I think I misunderstood the docs about uniqueness for multiple instances, I see now. 
Got it, thanks!
~s

**Comment by legomushroom** [comment]
Happy to help! 👍 🎉
